version: "3.9"

services:
  app:
    build: .
    container_name: travelers-app
    ports:
      - "80:5000" 
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
