export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_TRAVEL_DATA: 'SET_TRAVEL_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_TRAVEL_DATA: 'RESET_TRAVEL_DATA',
	ADD_MARKER: 'ADD_MARKER',
	SET_MARKERS: 'SET_MARKERS',
	SET_DREAM_DATA: 'SET_DREAM_DATA',
	RESET_DREAM_DATA: 'RESET_DREAM_DATA',
	SET_USER_ID: 'SET_USER_ID',
};
